from pathlib import Path
import json,html,shutil
R=Path(__file__).resolve().parents[3];P=R/'marketing/video/shorts/vela-growth-20';D=R/'build/launch/exports/vela-shorts-en';S=json.loads((P/'series.json').read_text());e=html.escape
cards=[]
for s in S:
 timings=''.join(f'<li><b>{b["start"]:g}–{b["start"]+b["duration"]:g}s</b> {e(" / ".join(b["text"]))}</li>' for b in s['beats'])
 cards.append(f'''<article id="{s['id']}" data-wave="{'first' if s['initialWave'] else 'next'}"><video src="{s['file']}" poster="previews/{s['id']}.jpg" preload="none" controls playsinline></video><div class="copy"><span class="tag">{s['id']} · {s['duration']:g}s {'· FIRST FIVE' if s['initialWave'] else ''}</span><h2>{e(s['hook'])}</h2><p class="who">{e(s['audience'])}</p><p>{e(s['hypothesis'])}</p><div class="proof"><strong>First 3 seconds</strong><p>{e(s['firstThreeSeconds'])}</p></div><div class="actions"><button onclick="playHook(this)">Play first 3 seconds</button><a href="{s['file']}" download>MP4</a><a href="{Path(s['file']).stem}.srt" download>Captions</a></div><details><summary>Beats and alternative hook</summary><p><strong>Alternative:</strong> {e(s['alternateHook'])}</p><ol>{timings}</ol></details><details><summary>Title and upload description</summary><p><strong>{e(s['title'])}</strong></p><pre>{e(s['description'])}</pre></details></div></article>''')
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Vela · 20 Shorts</title><style>
:root{--bg:#0d1118;--panel:#151c27;--ink:#f3f5f9;--muted:#aeb7c6;--blue:#80aaff;--line:#303947;color-scheme:dark}*{box-sizing:border-box}body{margin:0;padding:48px 5%;font:17px/1.55 -apple-system,BlinkMacSystemFont,Arial,sans-serif;background:var(--bg);color:var(--ink)}main{max-width:1260px;margin:auto}.tag{color:var(--blue);font-size:13px;letter-spacing:.12em;font-weight:700}h1{font-size:clamp(40px,6vw,76px);letter-spacing:-.05em;line-height:1.03}h2{font-size:32px;letter-spacing:-.035em;line-height:1.1;margin:18px 0}.intro{font-size:22px;max-width:800px}p{color:var(--muted)}a{color:var(--blue)}.strategy{border:1px solid var(--line);padding:28px;border-radius:20px;margin:28px 0 40px}.strategy h2{font-size:23px}nav,.actions{display:flex;gap:20px;align-items:center;flex-wrap:wrap}nav{margin:24px 0 40px}.actions{margin:24px 0}button{background:var(--blue);color:var(--bg);font:inherit;font-weight:650;border:0;padding:11px 18px;border-radius:30px;cursor:pointer}article{display:grid;grid-template-columns:minmax(230px,310px) 1fr;gap:38px;padding:26px;border:1px solid var(--line);border-radius:22px;background:var(--panel);margin-bottom:26px}article[hidden]{display:none}video{width:100%;aspect-ratio:9/16;border-radius:13px;display:block;background:black}.who{font-size:14px}.proof{border-left:3px solid var(--blue);padding-left:18px;margin:24px 0}.proof p{margin-bottom:0}.proof strong{font-size:14px}summary{cursor:pointer;padding:10px 0}pre{font:14px/1.6 inherit;white-space:pre-wrap;color:var(--muted)}li b{color:var(--blue);font-size:14px;display:inline-block;min-width:80px}li{margin-bottom:10px}ol{padding-left:20px}footer{margin:44px 0;font-size:14px;color:var(--muted)}@media(max-width:700px){body{padding:26px 5%}article{grid-template-columns:1fr;padding:18px;gap:18px}video{max-height:70vh}h2{font-size:28px}}
</style><main><header><span class="tag">VELA · ENGLISH SHORTS · 03 OCTOBER 2026</span><h1>Your files.<br>Your Jellyfin library.<br>One player.</h1><p class="intro">20 finished cuts, each with a first-frame hook, a visible payoff and a short closing over the real player.</p><p>1080 × 1920 · 30 fps · 13–15.5 seconds · Original music · English captions</p></header><section class="strategy"><h2>Start with five different reasons to watch.</h2><p>V01: free-app discovery. V02: Jellyfin meets local files. V03: controls disappear. V04: MKV utility. V07: external subtitles.</p><p>Publish the first wave individually, then compare stayed-to-watch, engaged viewing and audience fit. The remaining cuts are prepared options, not a schedule to publish blindly. No channel Analytics was accessed and no reach forecast is claimed.</p><p><a href="STRATEGY.md">Full strategy</a> · <a href="BEATS.md">All hooks and beats</a> · <a href="UPLOAD.csv" download>Upload table</a> · <a href="RESULTS.csv" download>Results worksheet</a> · <a href="HOOKS-20.jpg">Hook contact sheet</a></p></section><nav><button onclick="filter('first')">First five</button><button onclick="filter('all')">All 20</button></nav>'''+''.join(cards)+'''<footer>Prepared locally; nothing uploaded. YouTube guidance: <a href="https://support.google.com/youtube/answer/11914225?hl=en">Shorts discovery</a> · <a href="https://support.google.com/youtube/answer/12220281?hl=en">Metrics</a> · <a href="https://support.google.com/youtube/answer/13748639?hl=en">Clickable links</a>. Film credits and source acknowledgements accompany each upload description.</footer></main><script>
function filter(w){document.querySelectorAll('article').forEach(a=>a.hidden=w!=='all'&&a.dataset.wave!==w)}function playHook(b){let v=b.closest('article').querySelector('video');v.pause();v.currentTime=0;v.dataset.hook='1';v.play()}document.querySelectorAll('video').forEach(v=>{v.addEventListener('play',()=>document.querySelectorAll('video').forEach(x=>{if(x!==v)x.pause()}));v.addEventListener('timeupdate',()=>{if(v.dataset.hook==='1'&&v.currentTime>=3){v.pause();v.dataset.hook='0'}})});
</script></html>'''
(D/'INDEX.html').write_text(page)
for name in ['STRATEGY.md','BEATS.md','RESULTS.csv']:shutil.copy2(P/name,D/name)
print('Vela gallery and campaign files ready.')
