"""Twenty Vela creative treatments; public copy and timings are generated together."""
from pathlib import Path
import json,csv
R=Path(__file__).resolve().parents[3];P=R/'marketing/video/shorts/vela-growth-20';D=R/'build/launch/exports/vela-shorts-en'
CREDIT='Demo films: Sintel © Blender Foundation / durian.blender.org and Big Buck Bunny © 2008 Blender Foundation / www.bigbuckbunny.org (CC BY 3.0). Caminandes: Gran Dillama © Caminandes team / Blender Foundation, (CC) caminandes.com (CC BY-SA 3.0). Cropped/resized excerpts and demo artwork. This video composition: CC BY-SA 3.0, https://creativecommons.org/licenses/by-sa/3.0/. Vela branding and third-party UI/marks retain their own rights. Original Hauser music used with this production.\nBuilt on Swiftfin: https://github.com/jellyfin/Swiftfin . Vela is independent, not endorsed by Jellyfin or Swiftfin.'
def b(text,visual,duration=2.5,**kw):return dict(text=text.split('|'),visual=visual,duration=duration,**kw)
def s(i,slug,hook,alt,title,audience,hypothesis,proof,body,desc,ending='Vela.|Just watch.',track='D',priority=False):
 beats=[b(hook,proof[0],3)]+body+[b(ending,'local',2,cta=True)]
 return dict(id=f'V{i:02}',slug=slug,hook=hook.replace('|',' '),alternateHook=alt,title=title,audience=audience,hypothesis=hypothesis,firstThreeSeconds=proof[1],beats=beats,duration=sum(x['duration'] for x in beats),file=f'vela-{i:02}-{slug}.mp4',initialWave=priority,music=f'hauser-{track}.wav',musicOffset={'D':7,'E':15,'B':14,'F':0}[track],description=desc+'\n\nVela is a free, open-source Mac video player with Jellyfin built in. Vela 0.9.4 Beta · macOS 15.6+ · Apple silicon and Intel. A Jellyfin server is needed for the server-library features; local files need no server or account.\nDownload and details: https://ralleur.github.io/Vela/\n\n'+CREDIT+'\n\n#Vela #MacApps '+('#Jellyfin' if 'Jellyfin' in audience else '#OpenSource'))
S=[
s(1,'wait-this-is-free','Wait.|This is free?','A Pro unlock? There isn’t one.','A free Mac video player with Jellyfin built in','Mac app discovery','Price surprise earns entry; useful product proof prevents empty free-app bait.',('price','Live Vela playback from frame 0; FREE appears at 0.8s. The first body beat proves local/Jellyfin support.'),[b('Your local files.','file',2),b('Your Jellyfin library.','library',2),b('One player.|The whole app.','pair',2.5),b('No subscription.|No Pro unlock.','free',2.5)],'A proper Mac player, with local files and Jellyfin in the same app. The whole app is free.',track='D',priority=True),
s(2,'jellyfin-meet-downloads','Jellyfin.|Meet your Downloads.','Your Jellyfin client has a second job.','Jellyfin and local MKVs in one Mac player','Mac + Jellyfin users','Connect a familiar product to a specific missing everyday use.',('pair','A local-file picker and real Jellyfin library meet during the first 1.2s; source labels are visible from frame 0.'),[b('A film on|your server.','detail',2.5),b('A file on|your Mac.','file',2.5),b('The same|playback controls.','controlsStill',2.5),b('Both belong here.','local',2.5)],'Your files and your Jellyfin library lead to the same player. That is the idea behind Vela.',track='F',priority=True),
s(3,'watch-the-controls','Watch|the controls.','My favourite feature disappears.','The Mac video player that gets out of the way','Mac design and video viewers','A small, immediate visual payoff can hold interest without prior brand awareness.',('controls','An editorial wipe between matching real controls-visible/hidden captures starts at 0.6s and completes at 1.2s.'),[b('There when|you need them.','controlsStill',2.5),b('Gone when|you don’t.','clean',2.5),b('More room|for the film.','local',3),b('That’s the idea.','full',2)],'Vela’s controls are there when you need them, then make room for the film. The opening compares two matching captured player states.',track='E',priority=True),
s(4,'an-mkv-not-a-project','An MKV.|Not a project.','It’s a video file. Let’s watch it.','Open an MKV on Mac with Vela','Mac users with local video files','A familiar file-format irritation leads directly to successful playback.',('filePlay','The selected Sintel.mkv is shown immediately, followed at 1s by its actual Vela playback recording; this is an edit, not a latency test.'),[b('Open the video.','file',2),b('Vela plays it.','local',3),b('Subtitles?|Right here.','subtitles',2.5),b('Now watch.','clean',2.5)],'Open a local MKV in Vela and start watching. This shows the tested Sintel demo file, not a promise about every possible codec.',track='D',priority=True),
s(5,'why-switch-apps','Why am I|switching apps?','The video moved. Why should the player?','Local video or Jellyfin — why switch players?','Mac + Jellyfin users','A recognisable unnecessary decision makes the shared player valuable.',('sourceSwitch','Local and Jellyfin evidence cut at 0 and 1s, then share one player view at 2s.'),[b('This one lives|on my Mac.','file',2.5),b('That one lives|on my server.','library',2.5),b('I just want|to press play.','server',3),b('One familiar|place to watch.','controlsStill',2)],'The source of a video should not decide which app you open. Vela puts local files and your Jellyfin library together.',track='F'),
s(6,'no-account-just-play','No account.|Just press play.','A local video shouldn’t need a login.','Play local videos on Mac without an account','Mac users with local files','Remove one clear obstacle while qualifying the claim as local playback.',('filePlay','Local MKV evidence leads to real playback by 1s; a LOCAL FILES label scopes the no-account claim.'),[b('For a file|on your Mac…','file',2.5),b('…no server|is needed.','local',3),b('Open it.|Make yourself comfy.','clean',3)],'Local video playback in Vela needs no account or server. Connecting a Jellyfin library is an optional, separate path.',track='B'),
s(7,'subtitle-file-belongs-here','Your subtitle file|belongs here.','Got an SRT? Your player should take it.','Add external subtitles in Vela for Mac','Mac viewers using subtitle files','A specific useful answer can attract saves and relevant search interest.',('subtitleAdd','The real subtitle menu is already shown, with the Add Subtitle File option outlined at 0.6s.'),[b('Open the|subtitle menu.','subtitles',2.5),b('Add Subtitle File…','subtitleAdd',2.5),b('SRT · ASS/SSA · VTT','subtitleAdd',2.5),b('Your file.|Your subtitles.','local',2.5)],'Add an external SRT, ASS/SSA or VTT subtitle file in Vela. The menu is an actual app capture; the outline is an editorial highlight.',track='E',priority=True),
s(8,'local-or-server','Local or server?|Same player.','Two sources. One set of controls.','One Mac player for local files and Jellyfin','Mac + Jellyfin users','Make the central promise understandable as a comparison without lengthy setup.',('sourceSwitch','Source labels identify each real capture; local and server playback replace the source cards by 2s.'),[b('Local video.','local',2.5),b('Jellyfin video.','server',2.5),b('Same controls.|Same app.','controlsStill',3),b('Less switching.','pair',2)],'A local video and a film on your Jellyfin server use the same Vela player.',track='D'),
s(9,'where-is-pro','Where’s the|Pro version?','The whole app. No upgrade screen.', 'No Pro tier. The whole Mac app is free.','Mac app discovery','Answer a price objection, then show why the free app is worth considering.',('price','Real playback begins immediately; NO PRO TIER replaces the price question at 0.8s.'),[b('There isn’t one.','free',2),b('Local files.|Included.','file',2),b('Jellyfin.|Included.','library',2),b('The whole app.|Free.','pair',3)],'There is no Pro edition, subscription or in-app purchase in Vela. This is the whole app.',track='B'),
s(10,'your-mac-your-jellyfin','Your Mac.|Your Jellyfin library.','Jellyfin users: keep watching here.','A Jellyfin player for your Mac — meet Vela','Mac + Jellyfin users','Audience identity and recognisable library UI qualify viewers immediately.',('libraryHook','Actual Jellyfin home is visible on the first frame; the camera closes in on the Continue Watching row.'),[b('Your library.','library',2),b('Choose a film.','detail',2.5),b('Press play.','server',3),b('Local files|are welcome too.','file',2.5)],'Browse your Jellyfin library, open a film and watch in Vela on Mac. You can open local files in the same app.',track='F'),
s(11,'vlc-got-this-right','VLC got|one thing right.','A video player should play the file.','VLC got this right: just play the video','Mac users and open-source community','Familiarity opens the story; respectful attribution builds credibility.',('vlc','The statement sits over actual local playback; the answer JUST PLAY THE FILE appears within the first 1.2s.'),[b('Just play|the file.','local',2.5),b('Vela uses VLC|for local playback.*','controlsStill',3,footnote='*Default engine · compatibility depends on the file'),b('And brings|Jellyfin along.','library',2.5),b('Thank you,|VideoLAN.','vlc',2.5)],'Vela carries forward the expectation that a player should play the file. VLC is the default local engine; mpv is also bundled. Compatibility depends on the file. Thank you, VideoLAN: https://www.videolan.org/ and mpv: https://mpv.io/ .',track='D'),
s(12,'favourite-feature-disappears','My favourite feature|disappears.','A good player knows when to leave.','My favourite feature in this Mac player disappears','Mac design and indie-app audience','First-person curiosity resolves into a visible design choice.',('controls','Matching captured player states wipe from controls to film in the opening 1.2s.'),[b('Need a control?','controlsStill',2.5),b('It’s right there.','subtitles',2.5),b('Ready to watch?','clean',2.5),b('Just the film.','local',3)],'The point of the player is the video. Vela puts the controls within reach, then lets them get out of the way.',track='E'),
s(13,'did-not-build-alone','I didn’t build|this alone.','This Mac app started with Swiftfin.','Vela is built on Swiftfin — with gratitude','Open-source and indie-app community','An honest origin story earns trust and credits the people behind the useful product.',('upstream','Real Jellyfin UI appears immediately; Swiftfin → Vela is an editorial lineage label visible by 0.8s.'),[b('Swiftfin built|the foundation.','library',2.5),b('An Apple client|for Jellyfin.','server',2.5),b('Vela adds|local Mac files.','file',2.5),b('Open source.|Built together.','upstream',3)],'Vela is a fork of Swiftfin. Its Apple Jellyfin client foundation made this possible; Vela adds a broader Mac role with local-file playback. Thank you to the upstream contributors.',ending='Built on Swiftfin.|With gratitude.',track='B'),
s(14,'ui-can-leave','The movie’s good.|The UI can leave.','I came here to watch the film.','Less interface. More film. Vela for Mac.','Mac video viewers and design audience','A blunt visual statement makes unobtrusive UI emotionally legible.',('controls','Visible controls yield to the matching clean frame at 0.6–1.2s.'),[b('Pause.|Seek. Choose.','controlsStill',2.5),b('Then get|out of the way.','clean',2.5),b('A player that|lets you watch.','local',3)],'Vela keeps playback controls handy and makes space for the film when you are watching.',track='E'),
s(15,'one-shortcut','One shortcut.|Your local video.','Command–O. Pick a video. Watch.','Open a local video in Vela with Command–O','Mac keyboard users','A tiny workflow offers immediate practical value and a searchable promise.',('keyboard','⌘O appears at frame 0 with the actual Open Video picker; playback follows at 1.2s.'),[b('01  Press ⌘O.','keyboardStill',2.5),b('02  Pick your video.','file',2.5),b('03  Watch.','local',3),b('That’s the workflow.','clean',2)],'In Vela on Mac, Command–O opens the native Open Video picker. Pick a local file and watch. The edit shows captured states, not measured opening speed.',track='F'),
s(16,'remember-free-apps','Remember free|desktop apps?','Free used to mean the whole app.','A free Mac app with no subscription or Pro tier','Mac app discovery','Nostalgia opens the door; real current utility keeps the promise grounded.',('price','Actual Mac player footage from frame 0; THE WHOLE APP appears at 0.8s.'),[b('Here’s one.','local',2),b('Local videos.','file',2),b('Your Jellyfin library.','library',2),b('No subscription.|No Pro tier.','free',3)],'Free means the whole app. Vela plays local video on your Mac and connects to your Jellyfin library.',track='B'),
s(17,'which-language','Which language|do you want?','Your movie. Your subtitle choice.','Choose subtitles in Vela for Mac','Mac viewers using subtitles','Visible language options answer a real viewing preference without a broad feature list.',('subtitles','The actual embedded subtitle menu is visible from frame 0, with a gentle camera move toward the available options.'),[b('See the available|subtitle tracks.','subtitles',3),b('Or bring|your own file.','subtitleAdd',2.5),b('Then enjoy|the video.','local',3)],'Choose from subtitle tracks provided by your video, or add a supported subtitle file. Available languages depend on the media; Vela does not invent or automatically translate subtitles.',track='E'),
s(18,'server-movie-mac-player','Your server’s movie.|Your Mac’s player.','Keep your library. Enjoy the player.','Watch your Jellyfin library in Vela for Mac','Mac + Jellyfin users','Connect self-hosted ownership to the everyday viewing experience.',('libraryHook','The actual library is present on the first frame; the crop moves to its playable films.'),[b('Connect|your Jellyfin server.','library',2.5),b('Choose from|your own library.','detail',2.5),b('Make room|for the film.','server',3),b('Free Mac app.|Your server stays yours.','clean',2.5)],'Vela is a player for your existing Jellyfin server. Browse your library and watch in the same player that handles your local Mac files.',track='D'),
s(19,'file-tonight','A file tonight.|Jellyfin tomorrow.','Different source. Same movie night.','Local files tonight, Jellyfin tomorrow — same Mac app','Mac + Jellyfin users','An ordinary viewing routine makes the central product promise memorable.',('sourceSwitch','Local picker, Jellyfin library and shared player appear in that order during the opening 3s.'),[b('Tonight’s download.','file',2.5),b('Tomorrow’s|library pick.','detail',2.5),b('One player|for both evenings.','server',3),b('Just watch|the video.','local',2.5)],'Whether the video is a file on your Mac or a film on your Jellyfin server, Vela gives it the same player.',track='F'),
s(20,'wanted-one-player','I wanted|one player.','My Jellyfin client needed one more thing.','Why I built Vela: local files and Jellyfin in one player','Mac + Jellyfin users and indie-app audience','The maker’s specific problem frames a credible reason for the product to exist.',('pair','Actual local and Jellyfin source cards move toward a shared player within the opening.'),[b('For files|on my Mac.','file',2.5),b('For films|on my Jellyfin server.','library',2.5),b('Built on Swiftfin.','upstream',2.5),b('Free.|Ready for movie night.','local',3)],'I wanted my Jellyfin client to be useful when the video was just a file on my Mac. That became Vela, built on Swiftfin with gratitude.',track='B')
]
for item in S:
 at=0
 for beat in item['beats']:beat['start']=at;at+=beat['duration']
(P/'series.json').write_text(json.dumps(S,ensure_ascii=False,indent=2)+'\n')
(R/'build/launch/vela-growth-20/series.json').write_text(json.dumps(S,ensure_ascii=False,indent=2)+'\n')
with (D/'UPLOAD.csv').open('w',newline='') as f:
 w=csv.DictWriter(f,fieldnames=['id','file','title','description','hook','alternate_hook','initial_wave','duration']);w.writeheader()
 for x in S:w.writerow({k:x[k] for k in ['id','file','title','description','hook','duration']}|dict(alternate_hook=x['alternateHook'],initial_wave=x['initialWave']))
if not (P/'RESULTS.csv').exists():
 with (P/'RESULTS.csv').open('w',newline='') as f:
  keys=['id','published_url','published_at','window_hours','shown_in_feed','stayed_to_watch_pct','engaged_views','average_view_duration_s','average_percentage_viewed','subscribers_gained','likes','shares','useful_comments','traffic_source_notes','next_decision'];w=csv.DictWriter(f,fieldnames=keys);w.writeheader()
  for x in S:
   for window in [48,168]:w.writerow(dict(id=x['id'],window_hours=window))
def stamp(t):
 ms=round(t*1000);return f'{ms//3600000:02}:{ms//60000%60:02}:{ms//1000%60:02},{ms%1000:03}'
for x in S:
 (D/(Path(x['file']).stem+'.description.txt')).write_text(x['description']+'\n')
 captions='\n\n'.join(f'{i+1}\n{stamp(b["start"])} --> {stamp(b["start"]+b["duration"])}\n'+ '\n'.join(b['text']) for i,b in enumerate(x['beats']))+'\n'
 (D/(Path(x['file']).stem+'.srt')).write_text(captions)
beats=['# Vela: twenty hooks and exact beats','', 'The first five to test are V01, V02, V03, V04 and V07. Read STRATEGY.md for the release and measurement logic. All on-screen copy is English.','']
for x in S:
 beats += [f'## {x["id"]} · {x["title"]}',f'**Audience:** {x["audience"]}',f'**Why this may hold attention:** {x["hypothesis"]}',f'**Hook:** {x["hook"]}',f'**Alternate opening:** {x["alternateHook"]}',f'**0–3 seconds:** {x["firstThreeSeconds"]}', '', '| Time | On-screen words | Visual |','|---|---|---|']
 for b in x['beats']:beats.append(f'| {b["start"]:g}–{b["start"]+b["duration"]:g}s | {" / ".join(b["text"])} | {b["visual"]} |')
 beats += ['']
(P/'BEATS.md').write_text('\n'.join(beats)+'\n')
print(f'{len(S)} treatments; {min(s["duration"] for s in S)}–{max(s["duration"] for s in S)}s; upload copy and captions generated.')
