blank_issues_enabled: true
contact_links:
  - name: Jellyfin documentation
    url:  https://jellyfin.org/docs/general/getting-help.html
    about: Upstream Jellyfin documentation for server setup and interoperability
